
#ifndef __LOCALIZE_DEFINITION__
#define __LOCALIZE_DEFINITION__
QLangRes::LocalizationDefinition s_LocalizationDefs[] = {
    {("EN="), 1252,	("English"),							("english.txt"),					false, false},
    {("FR="), 1252,	("Français"),							("french.txt"),					false, false},
    {("ZH="), 950,	("中文繁體 "),						("chinese.txt"),					false, false},		// Big5
    {("CH="), 936,	("中文简体 "),						("chineseSimplified.txt"),		false, false},		// gb2312
    {("KOR"), 51949,	("한국어 "),							("korean.txt"),					false, false},		// euc-kr
    {("JPN"), 932,	("日本語 "),							("japanese.txt"),					false, false},		// Shift_JIS
    {("DE="), 1252,	("Deutsch"),							("german.txt"),					false, false},
    {("ES="), 1252,	("Español"),							("spanish.txt"),					false, false},
    {("IT="), 1252,	("Italiano"),							("italian.txt"),					false, false},
    {("PTG"), 1252,	("Português"),						("portuguese.txt"),				false, false},
    {("PTB"), 1252,	("Português brasileiro"),				("brazilian_portuguese.txt"),		false, false},
    {("NL="), 1252,	("Nederlands"),						("dutch.txt"),					false, false},
    {("RUS"), 1251,	("Русский"),							("russian.txt"),					false, false},
    {("PLK"), 1250,	("Polski"),							("polish.txt"),					false, false},
    {("CAT"), 1252,	("Català"),							("catalan.txt"),					false, false},
    {("CSY"), 1250,	("Česky"),							("czech.txt"),					false, false},
    {("HUN"), 1252,	("Magyar"),							("hungarian.txt"),				false, false},
    {("ROM"), 1250,	("Română"),							("romanian.txt"),					false, false},
    {("TRK"), 1254,	("Türkçe"),							("turkish.txt"),					false, false},
    {("FAR"), 65001,	("فارسی"),							("farsi.txt"),					true,  false},		// UTF-8
    {("UKR"), 1251,	("Українська"),						("ukrainian.txt"),				false, false},
    {("HEB"), 28598,	("עברית"),							("hebrew.txt"),					true,  false},		// ISO-8859-8
    {("NON"), 1252,	("Nynorsk"),							("nynorsk.txt"),					false, false},
    {("NOR"), 1252,	("Norsk"),							("norwegian.txt"),				false, false},
    {("==="), 1252,	("Occitan"),							("occitan.txt"),					false, false},
    {("THA"), 874,	("ไทย "),							("thai.txt"),						false, false},		// tis-620
    {("==="), 1252,	("Furlan"),							("friulian.txt"),					false, false},
    {("AR="), 1256,	("الْعَرَبيّة"),								("arabic.txt"),					true,  false},
    {("FIN"), 1252,	("Suomi"),							("finnish.txt"),					false, false},
    {("LTH"), 1257,	("Lietuvių"),							("lithuanian.txt"),				false, false},
    {("ELL"), 1253,	("Ελληνικά"),							("greek.txt"),					false, false},
    {("SV="), 1252,	("Svenska"),							("swedish.txt"),					false, false},
    {("GLC"), 28591,	("Galego"),							("galician.txt"),					false, false},		// iso-8859-1
    {("SLV"), 1250,	("Slovenščina"),						("slovenian.txt"),				false, false},
    {("SKY"), 1252,	("Slovenčina"),						("slovak.txt"),					false, false},
    {("DAN"), 1252,	("Dansk"),							("danish.txt"),					false, false},
    {("==="), 1252,	("Estremeñu"),						("extremaduran.txt"),				false, false},
    {("==="), 1252,	("Žemaitiu ruoda"),					("samogitian.txt"),				false, false},
    {("BGR"), 1251,	("Български"),						("bulgarian.txt"),				false, false},
    {("IND"), 1252,	("Bahasa Indonesia"),					("indonesian.txt"),				false, false},
    {("SQI"), 1252,	("Gjuha shqipe"),						("albanian.txt"),					false, false},
    {("HR="), 1250,	("Hrvatski jezik"),					("croatian.txt"),					false, false},
    {("KAT"), 65001,	("ქართული ენა "),						("georgian.txt"),					false, false},		// UTF-8
    {("EUQ"), 1252,	("Euskara"),							("basque.txt"),					false, false},
    {("ESS"), 1252,	("Español argentina"),				("spanish_ar.txt"),				false, false},
    {("BEL"), 1251,	("Беларуская мова"),					("belarusian.txt"),				false, false},
    {("SR="), 1252,	("Cрпски језик"),						("serbian.txt"),					false, false},
    {("MS="), 1252,	("Bahasa Melayu"),					("malay.txt"),					false, false},
    {("==="), 1252,	("Lëtzebuergesch"),					("luxembourgish.txt"),			false, false},
    {("==="), 1252,	("Tagalog"),							("tagalog.txt"),					false, false},
    {("AFK"), 1252,	("Afrikaans"),						("afrikaans.txt"),				false, false},
    {("KKZ"), 1252,	("Қазақша"),							("kazakh.txt"),					false, false},
    {("UZB"), 1252,	("O‘zbekcha"),						("uzbek.txt"),					false, false},
    {("UZB"), 1252,	("Ўзбекча"),							("uzbekCyrillic.txt"),			false, false},
    {("KYR"), 1252,	("Кыргыз тили"),						("kyrgyz.txt"),					false, false},
    {("MKI"), 1252,	("Македонски јазик"),					("macedonian.txt"),				false, false},
	// 2012/03/13 new support
    {("HYE"), 65001,	("Հայերեն"), 							("armenian.txt"), 				false, false},
    {("AZE"), 65001,	("Azərbaycan dili"), 					("azeri.txt"), 					false, false},
    {("BNG"), 65001,	("বাংলা"), 							("bengali.txt"), 					false, false},
    {("ETI"), 65001,	("eesti keel"), 						("estonian.txt"), 				false, false},
    {("GUJ"), 65001,	("ગુજરાતી"), 						("gujarati.txt"), 				false, false},
    {("HIN"), 65001,	("हिन्दी"), 							("hindi.txt"), 					false, false},
    {("ISL"), 65001,	("íslenska"), 						("icelandic.txt"), 				false, false},
    {("XHO"), 65001,	("isiXhosa"), 						("xhosa.txt"), 					false, false},
    {("ZUL"), 65001,	("isiZulu"), 							("zulu.txt"), 					false, false},
    {("KAN"), 65001,	("ಕನ್ನಡ"), 							("kannada.txt"), 					false, false},
    {("KNK"), 65001,	("कोंकणी"), 							("konkani.txt"), 					false, false},
    {("LVI"), 65001,	("Latviešu valoda"), 					("latvian.txt"), 					false, false},
    {("MYM"), 65001,	("മലയാളം"), 						("malayalam.txt"), 				false, false},
    {("MRI"), 65001,	("Te Reo Māori"), 					("maori.txt"), 					false, false},
    {("MLT"), 65001,	("Malti"), 							("maltese.txt"), 					false, false},
    {("MAR"), 65001,	("मराठी "), 							("marathi.txt"), 					false, false},
    {("MON"), 65001,	("Монгол"), 							("mongolian.txt"), 				false, false},
    {("PAN"), 65001,	("ਪੰਜਾਬੀ"), 							("punjabi.txt"), 					false, false},
    {("QU="), 65001,	("Qhichwa Simi"), 					("quechua.txt"), 					false, false},
    {("SAN"), 65001,	("संस्कृता"), 						("sanskrit.txt"), 				false, false},
    {("SM="), 65001,	("Sámegiella"), 						("sami.txt"), 					false, false},
    {("NSO"), 65001,	("Sesotho"), 							("sotho.txt"), 					false, false},
    {("TSN"), 65001,	("Setswana"), 						("tswana.txt"), 					false, false},
    {("SWK"), 65001,	("Kiswahili"), 						("swahili.txt"), 					false, false},
    {("SYR"), 65001,	("ܠܫܢܐ ܣܘܪܝܝܐ"), 						("syriac.txt"), 					false, false},
    {("TAM"), 65001,	("தமிழ்"), 							("tamil.txt"), 					false, false},
    {("TTT"), 65001,	("татарча"), 							("tatar.txt"), 					false, false},
    {("TEL"), 65001,	("తెలుగు"), 							("telugu.txt"), 					false, false},
    {("URD"), 65001,	("اردو"), 								("urdu.txt"), 					true,  false},
    {("VIT"), 65001,	("tiếng Việt"), 						("vietnamese.txt"), 				false, false},
    {("CYM"), 65001,	("Cymraeg"), 							("welsh.txt"), 					false, false},
    {("BSB"), 65001,	("Bosanski"), 						("bosnian.txt"), 					false, false},
    {("DIV"), 65001,	("ދިވެހި"), 							("divehi.txt"), 					false, false},
    {("FOS"), 65001,	("føroyskt"), 						("faeroese.txt"), 				false, false},
    {("==="), 65001,	("ייִדיש"), 							("yiddish.txt"), 					true,  false},

};

#endif // __LOCALIZE_DEFINITION__
