#ifndef __LOCALIZE_DEFINITION__
#define __LOCALIZE_DEFINITION__
QLangRes::LocalizationDefinition s_LocalizationDefs[] = {
        {"EN=", "English",                                  "english.txt",                          	false, false},
        {"FR=", "Français",                                 "french.txt",                           	false, false},
        {"ZH=", "中文繁體 ",                                 "chinese.txt",                          	false, false},        // Big5
        {"CH=", "中文简体 ",                                 "chineseSimplified.txt",                    false, false},		// gb2312
        {"KOR", "한국어 ",                                   "korean.txt",                          	false, false},		// euc-kr
        {"JPN", "日本語 ",                                   "japanese.txt",                         	false, false},        // Shift_JIS
        {"DE=", "Deutsch",                                  "german.txt",                           	false, false},
        {"ES=", "Español",                                  "spanish.txt",                          	false, false},
        {"IT=", "Italiano",                                 "italian.txt",                          	false, false},
        {"PTG", "Português",                                "portuguese.txt",                           false, false},
        {"PTB", "Português brasileiro",                     "brazilian_portuguese.txt",                 false, false},
        {"NL=", "Nederlands",                               "dutch.txt",                                false, false},
        {"RUS", "Русский",                                  "russian.txt",                              false, false},
        {"PLK", "Polski",                                   "polish.txt",                               false, false},
        {"CAT", "Català",                                   "catalan.txt",                              false, false},
        {"CSY", "Česky",                                    "czech.txt",                                false, false},
        {"HUN", "Magyar",                                   "hungarian.txt",                            false, false},
        {"ROM", "Română",                                   "romanian.txt",                         	false, false},
        {"TRK", "Türkçe",                                   "turkish.txt",                          	false, false},
        {"FAR", "فارسی",                                    "farsi.txt",                            	true,  false},        // UTF-8
        {"UKR", "Українська",                               "ukrainian.txt",                            false, false},
        {"HEB", "עברית",                                    "hebrew.txt",                           	true,  false},        // ISO-8859-8
        {"NON", "Nynorsk",                                  "nynorsk.txt",                          	false, false},
        {"NOR", "Norsk",                                    "norwegian.txt",                            false, false},
        {"===", "Occitan",                                  "occitan.txt",                          	false, false},
        {"THA", "ไทย ",                                      "thai.txt",                             	false, false},        // tis-620
        {"===", "Furlan",                                   "friulian.txt",                         	false, false},
        {"AR=", "الْعَرَبيّة",                              "arabic.txt",                           	true,  false},
        {"FIN", "Suomi",                                    "finnish.txt",                          	false, false},
        {"LTH", "Lietuvių",                                 "lithuanian.txt",                           false, false},
        {"ELL", "Ελληνικά",                                 "greek.txt",                            	false, false},
        {"SV=", "Svenska",                                  "swedish.txt",                          	false, false},
        {"GLC", "Galego",                                   "galician.txt",                         	false, false},        // iso-8859-1
        {"SLV", "Slovenščina",                              "slovenian.txt",                            false, false},
        {"SKY", "Slovenčina",                               "slovak.txt",                           	false, false},
        {"DAN", "Dansk",                                    "danish.txt",                           	false, false},
        {"===", "Estremeñu",                                "extremaduran.txt",                         false, false},
        {"===", "Žemaitiu ruoda",                           "samogitian.txt",                           false, false},
        {"BGR", "Български",                                "bulgarian.txt",                            false, false},
        {"IND", "Bahasa Indonesia",                         "indonesian.txt",                           false, false},
        {"SQI", "Gjuha shqipe",                             "albanian.txt",                         	false, false},
        {"HR=", "Hrvatski jezik",                           "croatian.txt",                         	false, false},
        {"KAT", "ქართული ენა ",                            "georgian.txt",                             false, false},        // UTF-8
        {"EUQ", "Euskara",                                  "basque.txt",                           	false, false},
        {"ESS", "Español argentina",                        "spanish_ar.txt",                           false, false},
        {"BEL", "Беларуская мова",                          "belarusian.txt",                           false, false},
        {"SR=", "Cрпски језик",                             "serbian.txt",                          	false, false},
        {"MS=", "Bahasa Melayu",                            "malay.txt",                            	false, false},
        {"===", "Lëtzebuergesch",                           "luxembourgish.txt",                        false, false},
        {"===", "Tagalog",                                  "tagalog.txt",                          	false, false},
        {"AFK", "Afrikaans",                                "afrikaans.txt",                            false, false},
        {"KKZ", "Қазақша",                                  "kazakh.txt",                           	false, false},
        {"UZB", "O‘zbekcha",                                "uzbek.txt",                            	false, false},
        {"UZB", "Ўзбекча",                                  "uzbekCyrillic.txt",                        false, false},
        {"KYR", "Кыргыз тили",                              "kyrgyz.txt",                           	false, false},
        {"MKI", "Македонски јазик",                         "macedonian.txt",                           false, false},
        // 2012/03/13 new support
        {"HYE", "Հայերեն",                                    "armenian.txt",                             false, false},
        {"AZE", "Azərbaycan dili",                          "azeri.txt",                                false, false},
        {"BNG", "বাংলা",                                      "bengali.txt",                              false, false},
        {"ETI", "eesti keel",                               "estonian.txt",                             false, false},
        {"GUJ", "ગુજરાતી",                                    "gujarati.txt",                             false, false},
        {"HIN", "हिन्दी",                                      "hindi.txt",                                false, false},
        {"ISL", "íslenska",                                 "icelandic.txt",                            false, false},
        {"XHO", "isiXhosa",                                 "xhosa.txt",                                false, false},
        {"ZUL", "isiZulu",                                  "zulu.txt",                                 false, false},
        {"KAN", "ಕನ್ನಡ",                                      "kannada.txt",                              false, false},
        {"KNK", "कोंकणी",                                     "konkani.txt",                              false, false},
        {"LVI", "Latviešu valoda",                          "latvian.txt",                              false, false},
        {"MYM", "മലയാളം",                                 "malayalam.txt",                            false, false},
        {"MRI", "Te Reo Māori",                             "maori.txt",                                false, false},
        {"MLT", "Malti",                                    "maltese.txt",                              false, false},
        {"MAR", "मराठी ",                                     "marathi.txt",                              false, false},
        {"MON", "Монгол",                                   "mongolian.txt",                            false, false},
        {"PAN", "ਪੰਜਾਬੀ",                                      "punjabi.txt",                             false, false},
        {"QU=", "Qhichwa Simi",                             "quechua.txt",                              false, false},
        {"SAN", "संस्कृता",                                     "sanskrit.txt",                             false, false},
        {"SM=", "Sámegiella",                               "sami.txt",                                 false, false},
        {"NSO", "Sesotho",                                  "sotho.txt",                                false, false},
        {"TSN", "Setswana",                                 "tswana.txt",                               false, false},
        {"SWK", "Kiswahili",                                "swahili.txt",                              false, false},
        {"SYR", "ܠܫܢܐ ܣܘܪܝܝܐ",                              "syriac.txt",                                 false, false},
        {"TAM", "தமிழ்",                                    "tamil.txt",                                 false, false},
        {"TTT", "татарча",                                  "tatar.txt",                                false, false},
        {"TEL", "తెలుగు",                                   "telugu.txt",                                 false, false},
        {"URD", "اردو",                                     "urdu.txt",                                 true,  false},
        {"VIT", "tiếng Việt",                               "vietnamese.txt",                           false, false},
        {"CYM", "Cymraeg",                                  "welsh.txt",                                false, false},
        {"BSB", "Bosanski",                                 "bosnian.txt",                              false, false},
        {"DIV", "ދިވެހި",                                       "divehi.txt",                              false, false},
        {"FOS", "føroyskt",                                 "faeroese.txt",                             false, false},
        {"===", "ייִדיש",                                   "yiddish.txt",                              true,  false},

};

#endif // __LOCALIZE_DEFINITION__
